[mongodb]
mongodb-dev.sandeepinfo.online

[catalogue]
catalogue-dev.sandeepinfo.online

[frontend]
frontend-dev.sandeepinfo.online

[redis]
redis-dev.sandeepinfo.online

[user]
user-dev.sandeepinfo.online

[cart]
cart-dev.sandeepinfo.online

[mysql]
mysql-dev.sandeepinfo.online

[shipping]
shipping-dev.sandeepinfo.online

[rabbitmq]
rabbitmq-dev.sandeepinfo.online

[payment]
payment-dev.sandeepinfo.online

[all:vars]


